# ================================================
# pytest.ini - Pytest Configuration File
# options to control execution of the test(s)
# Note: priority always given to command line arguments
# ================================================

[pytest]

# ===============================================
# General Options
# ===============================================
# -v : verbose - Run tests in verbose mode (shows detailed test names and results)
# --browser : Specify browser type (chromium, firefox, or webkit)
# --headed : Run browser in headed mode (shows browser UI)
# --base-url : Define the base URL for all tests
# Alternative URLs:
#   --base-url=http://localhost/opencart/upload/
#   --base-url=https://naveenautomationlabs.com/opencard

# ===============================================
# Captures and Reports (Debugging)
# ===============================================
# --video : Record video only if the test fails (retain-on-failure)
# --video-on : Capture video every time
# --screenshot : Capture screenshot only on failure (only-on-failure)
# --screenshot=on : Capture screenshot always
# --tracing : Save Playwright trace file only if the test fails
#   Note: view a trace as follows: playwright show-trace 'reports/traces/test_invalid_user_login_trace.zip'
#   Note: to view the traceback:                                            playwright show-trace 'reports/traces/your_test_trace.zip'
#   Alternatively use the following site: https://trace.playwright.dev/
# --html : Generate HTML report
# --self-contained-html : Embed all report assets (CSS, JS, images) inside the HTML
# --capture=tee-sys : Display console logs while also capturing them for reports
# --alluredir : Generate Allure-compatible results for advanced reporting
#   note: after running the test, generate the allure reports as follows:   allure generate reports/allure-results
#   next, launch/display the allure reports as follows:                     allure serve reports/allure-results 
# --tb: traceback options; --tb=short, --tb=long, --tb=line

addopts =
    -v
    --browser=chromium
    --headed
    --base-url=https://tutorialsninja.com/demo/
    --video=retain-on-failure
    --screenshot=only-on-failure
    --tracing=retain-on-failure
    --html=reports/myreport.html
    --self-contained-html
    --capture=tee-sys
    --alluredir=reports/allure-results
    --tb=long

# ===============================================
# Parallel Execution - number of threads/workers
# ===============================================
# -n=1 or --numprocesses : Run tests parallel
# Examples: -n=1 or --numprocesses=2

# ===============================================
# Test Grouping (Markers)
# ===============================================
# Use one of the commands below when running pytest:
# -m "sanity"
# -m "regression"
# -m "sanity or regression"
# -m "sanity and regression"
# -m "sanity and not regression"
# -m "regression and not sanity"
# -m "datadriven"
# -m "end_to_end"

# ===============================================
# Flaky Test Handling
# ===============================================
# --reruns 2 : Retry failed tests up to 2 times
# --reruns-delay 2 : Wait time before retrying failed tests

# ===============================================
# Custom Markers

# sanity        marks a sanity test (basic quick check)
# regression    marks a regressio ntest (full end-to-end validation)
# datadriven    marks a datadriven test
# end_to_end    marks end_to_end tests
# ===============================================

markers =
    sanity: Marks a sanity test (basic quick check)
    regression: Marks a regression test (full end-to-end validation)
    datadriven: Marks a datadriven test
    end_to_end: Marks end_to_end tests